### ISSUE TITLE
problem run the blobsaver (log)

### ISSUE THREAD

**Issue by alzahlof** [airsquared/blobsaver#583] opened 2023-06-17 15:30 UTC
hi, i have issue when i try to save the blob using blobsaver ... log :

tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.1-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
[TSSC] manually specified generator "0x9b8aa2ff5df2539f"
[TSSC] manually specified ECID to use, parsed "C708A00E1401E" to dec:3501437743087646 hex:c708a00e1401e
[TSSC] manually specified apnonce to use, parsed "0df18df34bfb3443c935b924dcf12e74ce8920cd52bbfd26e1e8d7a2572e0115" to hex:0df18df34bfb3443c935b924dcf12e74ce8920cd52bbfd26e1e8d7a2572e0115
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [ ] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked other open issues to see if my problem has already been reported
 - [ ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment] 2023-06-26 23:24
Duplicate of #577.

**Closed by airsquared** 2023-06-26 23:24 UTC
Labels: duplicate
