### ISSUE TITLE
an unknown error occurred

### ISSUE THREAD

**Issue by olivertzeng** [airsquared/blobsaver#605] opened 2023-08-04 14:34 UTC
**Describe the bug**
IDK

**Desktop:**
 - OS Version: Ventura 13.5 beta
 - iOS Device: 16.5

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.JsonParser.parseReader(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Network.makeJsonRequest(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getSignedBetas(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.syntaxError(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.checkLenient(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.doPeek(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.peek(Unknown Source)
	... 13 more

```

**Comment by gdwnldsKSC** [comment] 2023-08-05 04:47
Same issue when attempting to use the 'beta versions' checkbox.

W11 insider 25905.

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.JsonParser.parseReader(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Network.makeJsonRequest(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getSignedBetas(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.syntaxError(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.checkLenient(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.doPeek(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.peek(Unknown Source)
	... 13 more

**Comment by Genxster1998** [comment] 2023-08-05 13:20
+1

**Comment by airsquared** [comment] 2023-08-06 19:37
Duplicate of #603.

**Closed by airsquared** 2023-08-06 19:37 UTC
Labels: bug, duplicate
