### ISSUE TITLE
Automatic Folder Creation

### ISSUE THREAD

**Issue by SavageAUS** [airsquared/blobsaver#421] opened 2022-03-19 03:07 UTC
**Describe the what you'd like**
It would be nice to have the option to create folders for each version of the blobs that are saved.
Just a checkbox to create folders in case other users do not want to use it.

**Optional screenshot**
Add any screenshots about the feature request here.

**Comment by airsquared** [comment] 2022-04-10 23:16
Duplicate of #265 if I'm not mistaken?

**Closed** 2022-04-10 23:16 UTC
Labels: enhancement
