### ISSUE TITLE
Get Error: Unable to extract BuildManifest when trying to save blobs for Apple TV 4

### ISSUE THREAD

**Issue by cewong2** [airsquared/blobsaver#425] opened 2022-04-04 16:32 UTC
**Describe the bug**
When trying to save blobs for AppleTV 4 (2015) with All Signed Versions check, a popup returns with an Error, with the following message: Unable to extract BuildManifest. This seems to have been going on since 15.4 was released, it previously worked, last version of blobsaver and current (3.1) have had the same issue.

**Desktop:**
 - OS Version: MacOS 10.14.6 Mojave
 - iOS Device: AppleTV 4 (2015)

**Checklist (place an x between the brackets to mark as completed):**
 - [ X] I have made sure I am on the latest version of blobsaver
 - [X ] I have checked other open issues to see if my problem has already been reported
 - [X ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
iosVersions = [IOSVersion[versionString=15.4.1, ipswURL=https://updates.cdn-apple.com/2022FCSWinter/fullrestores/002-82887/6CDA7A9F-0866-417F-A440-E95C8D8A863B/AppleTV5,3_15.4.1_19L452_Restore.ipsw, signed=true], IOSVersion[versionString=15.4, ipswURL=https://updates.cdn-apple.com/2022FCSWinter/fullrestores/071-05901/6C60FB17-938B-4FD6-8E67-1FD2C2F0E3C7/AppleTV5,3_15.4_19L440_Restore.ipsw, signed=true], IOSVersion[versionString=13.4.8, ipswURL=http://updates-http.cdn-apple.com/2020SummerSeed/fullrestores/061-92142/5EB0BEFA-C8BC-4FF4-949A-D37D8776EEF1/AppleTV5,3_13.4.8_17M61_Restore.ipsw, signed=true], IOSVersion[versionString=10.2.2, ipswURL=http://appldnld.apple.com/tvos10.2.2/091-23452-20170720-5D53229C-6A56-11E7-8577-8B2C4A4DD6D5/AppleTV5,3_10.2.2_14W756_Restore.ipsw, signed=true]]
airsquared.blobsaver.app.TSS$TSSException: Unable to extract BuildManifest.
	at airsquared.blobsaver@3.1.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.1.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error on ZipFile ipsw
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.1.0/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	... 7 more
Caused by: java.io.IOException: local file header for Firmware/dfu/O? starts after central directory
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.sanityCheckLFHOffset(Unknown Source)
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.readCentralDirectoryEntry(Unknown Source)
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	... 10 more
```

**Comment by turlodales** [comment] 2022-04-08 02:02
snap same problem

OS Version: 12.4 Beta 1 (21F5048e) Monterey
iOS Device: AppleTV 4 (2015)

airsquared.blobsaver.app.TSS$TSSException: Unable to extract BuildManifest.
	at airsquared.blobsaver@3.1.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.1.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error on ZipFile ipsw
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.1.0/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	... 7 more
Caused by: java.io.IOException: local file header for Firmware/dfu/O? starts after central directory
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.sanityCheckLFHOffset(Unknown Source)
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.readCentralDirectoryEntry(Unknown Source)
	at blobsaver.merged.module@3.1.0/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	... 10 more

**Comment by airsquared** [comment] 2022-04-10 03:02
Are you still getting this error? I'm unable to reproduce this.

**Comment by turlodales** [comment] 2022-04-11 10:25
yes every time i try sadly.

would you like me to screen record what is happing?

**Comment by airsquared** [comment] 2022-04-14 02:38
Try [this beta](https://nightly.link/airsquared/blobsaver/workflows/main/master).

**Comment by cewong2** [comment] 2022-04-20 15:27
> 

This worked! Also like that I don't need to put in Beta ipsw's anymore! thank you!

**Comment by briankendall** [comment] 2022-04-21 16:17
For what it's worth, it fixed it for me too!

**Comment by turlodales** [comment] 2022-04-21 18:15
the beta version is 100% working on my Macbook pro M1 Max still need to try on my mac mini 2013 and my windows pc

**Comment by airsquared** [comment] 2022-04-30 07:26
Added in v3.2.0.

**Closed by airsquared** 2022-04-30 07:26 UTC
Labels: bug, Pending Release
