### ISSUE TITLE
Blobs don´t save automatically in background.

### ISSUE THREAD

**Issue by 420Dope** [airsquared/blobsaver#39] opened 2019-01-23 10:14 UTC
I have setup the background saving process weeks ago. Now iOS 12.1.3 is come out yesterday. But the blobs are not automatically saved. The check interval is 10 mins.

Now I have to consider, if apple f**ked up the signing again and opened the signing for olden firmwares, that Blobsaver don´t save these blobs automatically. I mean, isn´t it the main feature to save all signed blobs automatically?

Windows Server 2016
Blobsaver 2.2.1

**Comment by airsquared** [comment] 2019-01-24 03:43
It seems to work for me. Is your computer on sleep or have you already saved it at some point and deleted it?

**Comment by 420Dope** [comment] 2019-01-24 08:06
No, my computer (server) is not in sleep mode. I only work on my server with remote desktop. When i close remote desktop, the server is only locked and all programs are continue working.
I don´t have already saved the 12.1.3 blobs at some point and deleted it from the "save directory".

**Comment by airsquared** [comment] 2019-01-24 17:38
When you first configured saving in the background, did it work?

**Comment by 420Dope** [comment] 2019-01-24 19:09
Yes, first time i have configured it have saved all signed blobs. But not the new one yet.

**Comment by 420Dope** [comment] 2019-01-25 10:58
I have setup my 5 devices in the presets to save blobs from the last version. After that, i go into background settings and select all my 5 devices, change the frequency to 10 minutes and have start the background saving.
After starte the backgound saving. the notification on the right side of the screen pops up and say that the backgound saving for the devices is running. Then after i few minutes, blobsaver saves all blobs for the at this time signed iOS versions. I mean it was 12.1.1 and 12.1.2. and all was fine. I copied the saved blobs on my NAS and delete the blobs from the "saving directory". Blobsaver runs all the time in the background. After a reboot from the server, blobsaver starts automatically in the background.

So after a long time, apple releases iOS 2.1.3. and blobsaver should now save the blobs for iOS 12.1.3 automatically, because it was running in the background and the frequency is set to 10 minutes. However, blobsaver have don´t safe the blobs for iOS 12.1.3 until now (i have manually save them with TSSSaver so i am save).
But the idea i have running blobsaver in the background is, if apple f**ked the signing up again for maybe 30 minutes and i don´t see it fast enough, blobsaver should save all blobs for the signed iOS versions. I know that blobsaver will don´t save all blobs again which it have saved before, but i have don´t save the blobs for iOS 12.1 so blobsaver should save it.

Thats the story about it. I hope you can help me. I you need more informations, let me know.

**Comment by SwiftWinds** [comment] 2019-01-25 23:50
I can't seem to reproduce it. Maybe try clicking "force check"? Could you tell me what devices you're using?

**Comment by 420Dope** [comment] 2019-01-26 00:03
I habe some news. 
Today, i have reboot my Server. It was the first reboot apple releases iOS 12.1.3. and after the restart all blobs for 12.1.3 were saved. So there is maybe a bug in the frequency to check if new iOS versions are releases. Maybe blobsaver checks only for new iOS versions after when the background saving process is mee started. 

I think if i had pressed force check, blobsaver had saved the blobs. But it was not make sense to pressed force check, because blobsaver should automatically save new blobs.

**Comment by 420Dope** [comment] 2019-01-26 00:04
Ah, my devices are:
iPad Air 2
iPhone 5s
iPhone 6
iPhone 6s
iPhone 7

**Comment by airsquared** [comment] 2019-02-06 22:34
I've figured out the solution to this problem, will be fixed in the next version

**Comment by airsquared** [comment] 2019-02-09 06:22
This has been fixed in v2.2.3. Reopen this Github issue if the bug is still there.

**Closed by airsquared** 2019-02-09 06:22 UTC
Labels: bug

**Comment by airsquared** [comment] 2019-06-26 01:52
Please reopen the issue if you want to add another comment, as I won't be able to see it (which is why I just saw your comment two months later). Or you can just mention me with @airsquared so I'll get a notification that you commented.

I've changed the behavior recently, but previously it wouldn't save blobs for a version it's already saved in the background twice, even if you removed the files. (for example, if it has saved blobs for iOS 12.1.4 automatically once before, even if you delete the blobs from the folder it will not automatically save blobs for 12.1.4 again unless you manually do it).

Now, since v2.3.0, it will always save blobs for every signed version automatically.
