### ISSUE TITLE
Manifest error

### ISSUE THREAD

**Issue by Coll147** [airsquared/blobsaver#582] opened 2023-06-16 17:43 UTC
It is an error that appears when I try to save the shsh of beta versions of iOS, with normal versions it works fine.

![image](https://github.com/airsquared/blobsaver/assets/91793263/41856633-1bd5-4fba-9cf9-2c0ab9f6c59b)

 - OS Version: Windows 11
 - iOS Device: iOS16.5 > iPad6 Wifi

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.Debug-Build: Dec 14 2022 19:22:07-RELEASE
[TSSC] manually specified generator "0x3ce079fe8f36bdeb"
[TSSC] manually specified ECID to use, parsed "0x12090001200026" to dec:5076445204316198 hex:12090001200026
[TSSC] manually specified apnonce to use, parsed "cf61df181b6bf1089cd0ccc2ff0cb6253d593382d73bc9653449490ab530c479" to hex:cf61df181b6bf1089cd0ccc2ff0cb6253d593382d73bc9653449490ab530c479
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!

```

**Comment by airsquared** [comment] 2023-06-26 23:22
Duplicate of #577.

**Closed by airsquared** 2023-06-26 23:22 UTC
Labels: duplicate
