### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by anarchopossum** [airsquared/blobsaver#532] opened 2023-01-02 04:51 UTC
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
Cannot save blobs, stops midway

**Screenshots**

**Desktop:**
 - OS Version: Mac OS 13.1
 - iOS Device: Iphone 13 mini

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked other open issues to see if my problem has already been reported
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.saveBlobsSHSHHost(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson@2.10/com.google.gson.stream.JsonReader.beginObject(Unknown Source)
	at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	... 12 more

```

**Comment by airsquared** [comment] 2023-01-07 10:55
Duplicate of https://github.com/airsquared/blobsaver/issues/530. Please check there for more information.

**Closed by airsquared** 2023-01-07 10:55 UTC
Labels: duplicate
