### ISSUE TITLE
Unknown error, pasting log

### ISSUE THREAD

**Issue by GunpointGaming** [airsquared/blobsaver#442] opened 2022-06-07 21:05 UTC
**Describe the bug**
Failed to read from device

**Screenshots**

**Desktop:**
 - OS Version: 10.14.6
 - iOS Device: iPhone 13 Pro Max, iOS 15.4, iPhone 14,3

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
java.lang.UnsatisfiedLinkError: Unable to load library 'imobiledevice':
dlopen(/Applications/blobsaver.app/Contents/Frameworks/libimobiledevice.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib
dlopen(/Applications/blobsaver.app/Contents/Frameworks/libimobiledevice.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib
dlopen(/Users/gunpointg/Library/Frameworks/imobiledevice.framework/imobiledevice, 9): image not found
dlopen(/Library/Frameworks/imobiledevice.framework/imobiledevice, 9): image not found
dlopen(/System/Library/Frameworks/imobiledevice.framework/imobiledevice, 9): image not found
Native library (darwin-x86-64/libimobiledevice.dylib) not found in resource path ()
	at com.sun.jna@5.11.0/com.sun.jna.NativeLibrary.loadLibrary(Unknown Source)
	at com.sun.jna@5.11.0/com.sun.jna.NativeLibrary.getInstance(Unknown Source)
	at airsquared.blobsaver@3.2.0/airsquared.blobsaver.app.natives.NativeUtils.register(Unknown Source)
	at airsquared.blobsaver@3.2.0/airsquared.blobsaver.app.natives.Libimobiledevice.<clinit>(Unknown Source)
	at airsquared.blobsaver@3.2.0/airsquared.blobsaver.app.LibimobiledeviceUtil.lockdowndClientFromConnectedDevice(Unknown Source)
	at airsquared.blobsaver@3.2.0/airsquared.blobsaver.app.LibimobiledeviceUtil.enterRecovery(Unknown Source)
	at airsquared.blobsaver@3.2.0/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at airsquared.blobsaver@3.2.0/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Applications/blobsaver.app/Contents/Frameworks/libimobiledevice.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib
		at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
		... 13 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Applications/blobsaver.app/Contents/Frameworks/libimobiledevice.dylib, 9): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/blobsaver.app/Contents/Frameworks/libimobiledevice-glue-1.0.0.dylib
		at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
		... 13 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/gunpointg/Library/Frameworks/imobiledevice.framework/imobiledevice, 9): image not found
		at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
		... 13 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/imobiledevice.framework/imobiledevice, 9): image not found
		at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
		... 13 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/imobiledevice.framework/imobiledevice, 9): image not found
		at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
		... 13 more
	Suppressed: java.io.IOException: Native library (darwin-x86-64/libimobiledevice.dylib) not found in resource path ()
		at com.sun.jna@5.11.0/com.sun.jna.Native.extractFromResourcePath(Unknown Source)
		... 13 more
	Suppressed: java.lang.UnsatisfiedLinkError: Unable to load library 'imobiledevice-1.0':
dlopen(libimobiledevice-1.0.dylib, 9): image not found
dlopen(libimobiledevice-1.0.dylib, 9): image not found
dlopen(/Users/gunpointg/Library/Frameworks/imobiledevice-1.0.framework/imobiledevice-1.0, 9): image not found
dlopen(/Library/Frameworks/imobiledevice-1.0.framework/imobiledevice-1.0, 9): image not found
dlopen(/System/Library/Frameworks/imobiledevice-1.0.framework/imobiledevice-1.0, 9): image not found
Native library (darwin-x86-64/libimobiledevice-1.0.dylib) not found in resource path ()
		... 13 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libimobiledevice-1.0.dylib, 9): image not found
			at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
			... 13 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libimobiledevice-1.0.dylib, 9): image not found
			at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
			... 13 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/gunpointg/Library/Frameworks/imobiledevice-1.0.framework/imobiledevice-1.0, 9): image not found
			at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
			... 13 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/imobiledevice-1.0.framework/imobiledevice-1.0, 9): image not found
			at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
			... 13 more
		Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/imobiledevice-1.0.framework/imobiledevice-1.0, 9): image not found
			at com.sun.jna@5.11.0/com.sun.jna.Native.open(Native Method)
			... 13 more
		Suppressed: java.io.IOException: Native library (darwin-x86-64/libimobiledevice-1.0.dylib) not found in resource path ()
			at com.sun.jna@5.11.0/com.sun.jna.Native.extractFromResourcePath(Unknown Source)
			... 13 more
```

**Comment by airsquared** [comment] 2022-06-15 01:03
Duplicate of #428; please see my comment on the issue there.

**Closed by airsquared** 2022-06-15 01:03 UTC
Labels: bug
