### ISSUE TITLE
BlobSaver 2.5.0 fails saving iOS 12.x blobs for iPad Air, 2.4.1 works fine.

### ISSUE THREAD

**Issue by wmxp** [airsquared/blobsaver#159] opened 2020-05-21 04:23 UTC
**Describe the bug**
Attempted to use BlobSaver 2.5.0 to save blobs for my iPad Air Wifi, ending with 12.x based iOS support. Spits back a a generic failed error message. Downgrading back to BlobSaver 2.4.1 allows for process to complete successfully again.

**Screenshots**
![image](https://user-images.githubusercontent.com/30638431/82522898-9d8efe00-9adf-11ea-8671-dae927f38ce7.png)

**Desktop:**
 - OS Version: Windows 10 version 1909 build 18363.836
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
Version: 0ab4c4452a5a6a4f48ab7039560456051348b657 - 1
libfragmentzip version: 0.1-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "674899CA5C8" to dec:7097594717640 hex:674899ca5c8
[TSSC] opening C:\Users\Kelsey\AppData\Local\Temp\BuildManifest7807070674886000364.plist
[TSSR] LOG: device iPad4,1 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] LOG: device iPad4,1 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)

```

**Comment by airsquared** [comment] 2020-06-03 18:26
Closing as duplicate of #144. (please see that issue for updates)

**Closed** 2020-06-03 18:26 UTC
Labels: duplicate
