### ISSUE TITLE
Manisfest error

### ISSUE THREAD

**Issue by Taunty** [airsquared/blobsaver#580] opened 2023-06-12 23:10 UTC
**Describe the bug**
It says "Failed to load manisfest" when I start saving the blobs

**Screenshots**
![error](https://github.com/airsquared/blobsaver/assets/9028907/6906d194-227f-4feb-94b5-0ec5fc9aa8e3)

**Desktop:**
 - OS Version: Windows 10 latest version
 - iOS Device: 15.0.1

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.Debug-Build: Dec 14 2022 19:22:07-RELEASE
[TSSC] manually specified generator "0xe906c6623303e986"
[TSSC] manually specified ECID to use, parsed "1808C62E07802E" to dec:6765046709846062 hex:1808c62e07802e
[TSSC] manually specified apnonce to use, parsed "d23037e8d85e1e17ba99a571b355b67ac26a3fa36b464945d4246868db0096bb" to hex:d23037e8d85e1e17ba99a571b355b67ac26a3fa36b464945d4246868db0096bb
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!

```

**Comment by gotspatel** [comment] 2023-06-13 05:48
+1

**Comment by SGprooo** [comment] 2023-06-13 20:11
+1

**Comment by mattsblack** [comment] 2023-06-14 15:01
+1

**Comment by 21mtd** [comment] 2023-06-15 10:47
Have the same problem, can't (auto)save blobs, only 2/5 devices got this error

iPhone XS
```
tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.Debug-Build: Dec 14 2022 19:22:07-RELEASE
[TSSC] manually specified generator "0x61d4aceed536d49a"
[TSSC] manually specified ECID to use, parsed "1a34591eba002e" to dec:7375906766716974 hex:1a34591eba002e
[TSSC] manually specified apnonce to use, parsed "636b3387c155e566e44ec3fc2b5ea33119930b90571d1e7a3cc2fe095b70d80b" to hex:636b3387c155e566e44ec3fc2b5ea33119930b90571d1e7a3cc2fe095b70d80b
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!
```
iPhone 14 Pro Max
```
tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.Debug-Build: Dec 14 2022 19:22:07-RELEASE
[TSSC] manually specified generator "0x4680dbeb6205f3cc"
[TSSC] manually specified ECID to use, parsed "1265200E38C01E" to dec:5177737932750878 hex:1265200e38c01e
[TSSC] manually specified apnonce to use, parsed "45d15efeb75ddc606a2e2699468fa54554cf664bbde0580e218e41a5078648b6" to hex:45d15efeb75ddc606a2e2699468fa54554cf664bbde0580e218e41a5078648b6
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!
```

**Comment by chrisharper22** [comment] 2023-06-20 21:33
+1 for me as well.

```tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.1-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
[TSSC] manually specified ECID to use, parsed "11196E3681002E" to dec:4813035755601966 hex:11196e3681002e
[TSSC] manually specified apnonce to use, parsed "ab88a1285569f02050530fa1e28bcb0fd801e3e8586604784c8d80cfcae7e658" to hex:ab88a1285569f02050530fa1e28bcb0fd801e3e8586604784c8d80cfcae7e658
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!
```

**Comment by airsquared** [comment] 2023-06-26 23:22
Duplicate of #577.

**Closed by airsquared** 2023-06-26 23:22 UTC
Labels: bug
