### ISSUE TITLE
“blobsaver” is damaged and can’t be opened. 3.5.1 (Apple Silicon)

### ISSUE THREAD

**Issue by Spades804** [airsquared/blobsaver#594] opened 2023-07-07 10:55 UTC
**Describe the bug**
Crash with "Blobsaver.app" is damaged. Problem with Apple Silicon version of blobsaver on M1 mac. File is not corrupted and has been downloaded several times.

**Screenshots**
<img width="262" alt="Screenshot 2023-07-07 at 6 50 05 AM" src="https://github.com/airsquared/blobsaver/assets/138874653/f82e5eae-5c2c-459c-8adc-311bd5d31b91">

**Desktop:**
 - OS Version: Ventura 13.4

**Checklist (place an x between the brackets to mark as completed):**
 - [ X ] I have made sure I am on the latest version of blobsaver
 - [ X ] I have checked other open issues to see if my problem has already been reported
 - [ X ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by nmka55** [comment] 2023-07-07 14:00
As written in troubleshooting, run this command from terminal:

`xattr -cr /Applications/blobsaver.app`

**Comment by airsquared** [comment] 2023-07-09 02:09
Duplicate of #589.

**Closed by airsquared** 2023-07-09 02:09 UTC
Labels: duplicate
