### ISSUE TITLE
error

### ISSUE THREAD

**Issue by isaias78** [airsquared/blobsaver#608] opened 2023-08-09 13:02 UTC
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.JsonParser.parseReader(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Network.makeJsonRequest(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getSignedBetas(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.syntaxError(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.checkLenient(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.doPeek(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.peek(Unknown Source)
	... 13 more

**Comment by airsquared** [comment] 2023-08-11 02:01
Duplicate of #603.

**Closed by airsquared** 2023-08-11 02:01 UTC
Labels: duplicate
