### ISSUE TITLE
Error saving

### ISSUE THREAD

**Issue by MariusSolaat** [airsquared/blobsaver#13] opened 2018-10-09 12:00 UTC
![1](https://user-images.githubusercontent.com/20828176/46668039-a8777200-cbcb-11e8-8a76-d5ab22954bab.PNG)
![2](https://user-images.githubusercontent.com/20828176/46668040-a8777200-cbcb-11e8-97d5-a0c47d74640f.PNG)

On newest windows 10 update

**Comment by airsquared** [comment] 2018-10-09 18:22
Thanks for submitting a bug report. It'll be fixed in the next version. I'll close this issue(duplicate of #12).

**Closed** 2018-10-09 18:22 UTC

**Comment by airsquared** [comment] 2018-10-18 04:34
Just so you know, this has been fixed in v2.2.1.
