### ISSUE TITLE
lockdown weeor code +-23

### ISSUE THREAD

**Issue by mutantminecart** [airsquared/blobsaver#288] opened 2021-05-28 14:40 UTC
**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:ios 14.5.1
 - iOS Device:iphone se 2

**Checklist (place an x between the brackets to mark as completed):**
 - [x ] I have made sure I am on the latest version of blobsaver
 - [x ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x
![Capture](https://user-images.githubusercontent.com/84979631/120000574-ce720080-bf87-11eb-8c71-54c31ebaacbf.PNG)
] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment] 2021-05-28 16:07
This is a duplicate of #258 and has also been fixed in the latest v3.0 beta.

**Closed by airsquared** 2021-05-28 16:07 UTC
Labels: duplicate
