### ISSUE TITLE
apple TV 4 wont save blobs

### ISSUE THREAD

**Issue by billymac101** [airsquared/blobsaver#181] opened 2020-06-11 14:05 UTC
**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

Saving Apple TV blob fails, this has happened in earlier versions, sometimes it works mostly it does not

**Screenshots**

**Desktop:**
 - OS Version: Win 7 Ultimate
 - iOS Device: (if applicable) 

**Checklist (place an x between the brackets to mark as completed):**
 - [ x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [ x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.

Version: 0ab4c4452a5a6a4f48ab7039560456051348b657 - 1
libfragmentzip version: 0.1-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "598C247BE826" to dec:98458442393638 hex:598c247be826
[TSSC] opening C:\Users\Billymac\AppData\Local\Temp\BuildManifest2692870594663233635.plist
[TSSR] LOG: device Appletv5,3 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] LOG: device Appletv5,3 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)

```

**Comment by airsquared** [comment] 2020-06-11 20:46
Duplicate of #144. Please see that issue for updates.

**Closed by airsquared** 2020-06-11 20:46 UTC
Labels: duplicate
