### ISSUE TITLE
Some path with variables caused java exception in v3.4.0

### ISSUE THREAD

**Issue by rtxbae** [airsquared/blobsaver#523] opened 2022-12-14 04:29 UTC
**Describe the bug**
I got an java exception in log if I goes with this saving path for blobs:
```
D:\Softwares\blobs\iPhoneX\${MajorVersion}\${FullVersionString}
```
I have no idea why since my iPad works just fine with
```
D:\Softwares\blobs\iPadPro\${MajorVersion}\${FullVersionString}
```

**Desktop:**
 - OS Version: Windows 10 21H2
 - iOS Device: iPhone X

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml@19/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@19/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls@19/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@19/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@19/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base@19/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml@19/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	... 47 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/java.util.ImmutableCollections$MapN.<init>(Unknown Source)
	at java.base/java.util.Map.of(Unknown Source)
	at airsquared.blobsaver@3.4.0/airsquared.blobsaver.app.TSS.parsePath(Unknown Source)
	at airsquared.blobsaver@3.4.0/airsquared.blobsaver.app.TSS.<init>(Unknown Source)
	at airsquared.blobsaver@3.4.0/airsquared.blobsaver.app.TSS$Builder.build(Unknown Source)
	at airsquared.blobsaver@3.4.0/airsquared.blobsaver.app.Controller.createTSS(Unknown Source)
	at airsquared.blobsaver@3.4.0/airsquared.blobsaver.app.Controller.goButtonHandler(Unknown Source)
	... 54 more
```

**Comment by airsquared** [comment] 2022-12-14 19:38
This is a duplicate of #519.

**Closed by airsquared** 2022-12-14 19:38 UTC
Labels: bug
