### ISSUE TITLE
The iOS version is not being signed for device iPhone12,1

### ISSUE THREAD

**Issue by Demoxing** [airsquared/blobsaver#347] opened 2021-09-21 02:37 UTC
I am using the blobsaver from the first version but never faced this error before. after successfully getting the APNONCE when I press "GO," I am facing this error "The iOS version is not being signed for device iPhone12,1". 

![Screenshot 2021-09-21 at 8 00 11 AM](https://user-images.githubusercontent.com/53024273/134103180-0bbda617-6fcb-4481-a57f-a0017e43a4e0.png)

macOS Big Sur v11.6
iPhone 11 v14.4

 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment] 2021-09-21 04:46
Duplicate of #342 and fixed in v3.0.3.

**Closed by airsquared** 2021-09-21 04:46 UTC
Labels: duplicate
