### ISSUE TITLE
Can't save blobs on blobsaver v3.4.1

### ISSUE THREAD

**Issue by jakche** [airsquared/blobsaver#531] opened 2023-01-02 02:35 UTC
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
Can't save blobs. First time I tried to save it was stuck on saving blobs, spining forever.

**Screenshots**
![image](https://user-images.githubusercontent.com/70672583/210191593-e48db40a-909e-4523-963b-930275173067.png)

**Desktop:**
 - OS Version: Windows 10
 - iOS Device: (if applicable) All devices

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.saveBlobsSHSHHost(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson@2.10/com.google.gson.stream.JsonReader.beginObject(Unknown Source)
	at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	... 12 more
`
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment] 2023-01-07 10:56
Duplicate of https://github.com/airsquared/blobsaver/issues/530. Please check there for more information.

**Closed by airsquared** 2023-01-07 10:56 UTC
Labels: duplicate
