### ISSUE TITLE
IOS Version Not Signed

### ISSUE THREAD

**Issue by takingkeysyt** [airsquared/blobsaver#345] opened 2021-09-21 01:00 UTC
I was trying to make a blob file and it said my ios was un signed even though its 14.8 which is signed.

 - OS Version: 14.8
 - iOS Device: XR
 
**Checklist (place an x between the brackets to mark as completed):**
 - [x ] I have made sure I am on the latest version of blobsaver
 - [x ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [ x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**

iosVersions = [IOSVersion[versionString=15.0, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-02965/E21A0F85-CE8B-410B-96E1-E367D5619112/iPhone11,8,iPhone12,1_15.0_19A346_Restore.ipsw, signed=true], IOSVersion[versionString=14.8, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-97929/2567B0BA-F9C0-4181-9D2B-E4535D65518B/iPhone11,8,iPhone12,1_14.8_18H17_Restore.ipsw, signed=true], IOSVersion[versionString=14.7.1, ipswURL=https://updates.cdn-apple.com/2021SummerFCS/fullrestores/071-73868/321919C4-1F21-4387-936D-B72374C39DD6/iPhone11,8,iPhone12,1_14.7.1_18G82_Restore.ipsw, signed=true]]
Extracted to C:\Users\adida\AppData\Local\Temp\BuildManifest5627126483820977294.plist
Running: [C:\Program Files\blobsaver\lib\tsschecker.exe, --nocache, --save, --device, iPhone11,8, --ecid, 146C262645002E, --save-path, C:\Users\adida\Downloads, --boardconfig, n841ap, --apnonce, 3a05066713f0ff3d141ab40544129b5b9329374eed553a37f4d172c48e8ec8c8, --generator, 0x9f773ea559fd9eb0, --build-manifest, C:\Users\adida\AppData\Local\Temp\BuildManifest5627126483820977294.plist]
tsschecker version: 322.0-d7f6161052c973350fd7134a0b104fa2cb01d65f
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8
[TSSC] manually specified generator "0x9f773ea559fd9eb0"
[TSSC] manually specified ECID to use, parsed "146C262645002E" to dec:5748410640826414 hex:146c262645002e
[TSSC] manually specified apnonce to use, parsed "3a05066713f0ff3d141ab40544129b5b9329374eed553a37f4d172c48e8ec8c8" to hex:3a05066713f0ff3d141ab40544129b5b9329374eed553a37f4d172c48e8ec8c8
[TSSC] opening C:\Users\adida\AppData\Local\Temp\BuildManifest5627126483820977294.plist
[TSSR] Checking BuildIdentity 0
[WARNING] [TSSR] Could not get RestoreBehavior
[TSSR] Checking BuildIdentity 1
[TSSR] Checking BuildIdentity 2
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

iOS 15.0 for device iPhone11,8 IS NOT being signed!
airsquared.blobsaver.app.TSS$TSSException: The iOS version is not being signed for device iPhone11,8
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.parseTSSLog(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by airsquared** [comment] 2021-09-21 04:45
Duplicate of #342 and fixed in v3.0.3.

**Closed by airsquared** 2021-09-21 04:45 UTC
Labels: duplicate
