### ISSUE TITLE
Blobsaver is running but I cannot open the window

### ISSUE THREAD

**Issue by Dolyfin** [airsquared/blobsaver#125] opened 2019-11-14 06:52 UTC
**Describe the bug**
Blobsaver is already running, Exiting. I have no way of turning off the background mode and nothing shows up in task manager that i am able to close. This happened after I put it in background mode.

**Desktop (please complete the following information):**
 - OS: win 10 1903
 - App version 2.4

**Comment by airsquared** [comment] 2020-02-10 01:39
Does the issue persist after restarting your computer?

**Comment by airsquared** [comment] 2020-02-11 21:01
Closing this issue as a duplicate of #84.

**Closed by airsquared** 2020-02-11 21:01 UTC
Labels: bug
