### ISSUE TITLE
iPhone 13 Pro Max blob save failed.

### ISSUE THREAD

**Issue by anonypublic** [airsquared/blobsaver#359] opened 2021-09-30 23:05 UTC
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [ ] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked other open issues to see if my problem has already been reported
 - [ ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by Macleykun** [comment] 2021-10-03 20:32
Is there any info we can provide to help with this?

**Comment by evanheckert** [comment] 2021-10-05 20:59
FWIW, it seemed to save successfully for my 13 Pro Max

**ECID:** (clicked 'read from device')
**Manually Specify Identifier:** iPhone14,3
**All Signed Versions**
**Internal Name/Board Configuration:** D64AP (I found this in the Geekbench app on the device)
**Specify APNonce:**  I entered 0x1111111111111111 for the generator, then clicked "Read From Device", which populated the APNonce as well as a new generator. 

I'm not 100% certain that the generator/APNonce situation won't change, given what I read in another issue, but at least it seemed to save successfully nonetheless.

**Comment by tonyintn** [comment] 2021-10-05 23:19
I would not put anything in the generator I would let it generate(Read from device), unjailbroken and it will get the apnonce because there is no way that it is jailbroken at that firmware anyway.

**Comment by airsquared** [comment] 2021-10-06 02:36
> Is there any info we can provide to help with this?

I just hadn't gotten around to adding the devices myself, but someone created a PR so I'll release this shortly.

**Comment by airsquared** [comment] 2021-10-06 02:37
Duplicate of #354.

**Closed by airsquared** 2021-10-06 02:37 UTC
Labels: duplicate
