### ISSUE TITLE
Failed to load manifest.

### ISSUE THREAD

**Issue by alxandercode** [airsquared/blobsaver#611] opened 2023-08-13 00:48 UTC
I tried saving SHSH blobs for the iPad 2 (mid 2012) and everytime I press "go" I get "Failed to load manifest".
![Screen Shot 2023-08-12 at 8 43 42 PM](https://github.com/airsquared/blobsaver/assets/142126935/b2289e0d-fc88-431b-a719-bbdc29e1628f)

 - OS Version: Mac OS X 10.15.7 and Windows 11 on bootcamp
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x ] I have made sure I am on the latest version of blobsaver
 - [ x] I have checked other open issues to see if my problem has already been reported
 - [x ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.1-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
[TSSC] manually specified generator "0x0000000000000000"
[TSSC] manually specified ECID to use, parsed "FF0962DCD" to dec:68460883405 hex:ff0962dcd
[TSSC] manually specified apnonce to use, parsed "42975f487e34bcc3730b42460f390d21f8f868d5" to hex:42975f487e34bcc3730b42460f390d21f8f868d5
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!

```

**Comment by airsquared** [comment] 2023-08-13 00:51
Likely a duplicate of #592. Please check the solution there.

**Closed** 2023-08-13 00:54 UTC
Labels: bug
