### ISSUE TITLE
The iOS/iPadOS version is not being signed for device

### ISSUE THREAD

**Issue by carlosrc1990** [airsquared/blobsaver#344] opened 2021-09-20 20:57 UTC
**Describe the bug**
I cannot save blobs in my iPhone or mi iPad. I saved my devices in blobsaver months ago

**Screenshots**

**Desktop:**
 - OS Version:macOS 11.2.1
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x ] I have made sure I am on the latest version of blobsaver
 - [ x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
iosVersions = [IOSVersion[versionString=15.0, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-02934/7805E229-0D8B-4FFF-A39B-79457FFFEDD3/iPad_Pro_A12X_A12Z_15.0_19A346_Restore.ipsw, signed=true], IOSVersion[versionString=14.8, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98112/31AE81F4-E266-47A8-8A65-288001F0CEEC/iPad_Pro_A12X_A12Z_14.8_18H17_Restore.ipsw, signed=true], IOSVersion[versionString=14.7.1, ipswURL=https://updates.cdn-apple.com/2021SummerFCS/fullrestores/071-74165/74E0327B-42EF-461E-B03F-7538AB4100BC/iPad_Pro_A12X_A12Z_14.7.1_18G82_Restore.ipsw, signed=true]]
Extracted to /var/folders/pz/s_t4pb8x3812k34c4q313spw0000gn/T/BuildManifest7348473225335314706.plist
Running: [/Applications/blobsaver.app/Contents/MacOS/tsschecker, --nocache, --save, --device, iPad8,1, --ecid, 1D50A21E87002E, --save-path, /Users/carlosrodriguezcortes/Desktop/iPad SHSH, --boardconfig, j317ap, --apnonce, a5298d3147c6c172f491ebcac9312b65729a353af8c330799c2ad4adfeea3b06, --generator, 0x4e5d57dd938fc688, --build-manifest, /private/var/folders/pz/s_t4pb8x3812k34c4q313spw0000gn/T/BuildManifest7348473225335314706.plist]
tsschecker version: 1.0-4d5a39487d7f49c8cd23874c05c59dd38d010432
Libfragmentzip version: 7951fa1e40415a630cd2d4401b2ebb261b0a46a2 - 53
[TSSC] manually specified generator "0x4e5d57dd938fc688"
[TSSC] manually specified ECID to use, parsed "1D50A21E87002E" to dec:8251431551696942 hex:1d50a21e87002e
[TSSC] manually specified apnonce to use, parsed "a5298d3147c6c172f491ebcac9312b65729a353af8c330799c2ad4adfeea3b06" to hex:a5298d3147c6c172f491ebcac9312b65729a353af8c330799c2ad4adfeea3b06
[TSSC] opening /private/var/folders/pz/s_t4pb8x3812k34c4q313spw0000gn/T/BuildManifest7348473225335314706.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] LOG: device iPad8,1 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

iOS 15.0 for device iPad8,1 IS NOT being signed!
airsquared.blobsaver.app.TSS$TSSException: The iOS/iPadOS version is not being signed for device iPad8,1
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.parseTSSLog(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)





iosVersions = [IOSVersion[versionString=15.0, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-03652/02507F5B-9411-410B-B837-C16AD6E54410/iPhone13,2,iPhone13,3_15.0_19A346_Restore.ipsw, signed=true], IOSVersion[versionString=14.8, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98054/06E594D3-1C74-4192-A0DE-38C0B0AB28BD/iPhone13,2,iPhone13,3_14.8_18H17_Restore.ipsw, signed=true], IOSVersion[versionString=14.7.1, ipswURL=https://updates.cdn-apple.com/2021SummerFCS/fullrestores/071-73682/4FEC25C8-8745-471E-A8DE-EF7572030F44/iPhone13,2,iPhone13,3_14.7.1_18G82_Restore.ipsw, signed=true]]
tsschecker = /Applications/blobsaver.app/Contents/MacOS/tsschecker
Extracted to /var/folders/pz/s_t4pb8x3812k34c4q313spw0000gn/T/BuildManifest4816493452694535719.plist
Running: [/Applications/blobsaver.app/Contents/MacOS/tsschecker, --nocache, --save, --device, iPhone13,3, --ecid, 1C48C81E22001E, --save-path, /Users/carlosrodriguezcortes/Desktop/iPhone SHSH, --boardconfig, d53pap, --apnonce, b0f3bab987cf096181fc2103182f271e91a7f9047386d02553ad9b48f96191b8, --generator, 0x1c65b4722da881fe, --build-manifest, /private/var/folders/pz/s_t4pb8x3812k34c4q313spw0000gn/T/BuildManifest4816493452694535719.plist]
tsschecker version: 1.0-4d5a39487d7f49c8cd23874c05c59dd38d010432
Libfragmentzip version: 7951fa1e40415a630cd2d4401b2ebb261b0a46a2 - 53
[TSSC] manually specified generator "0x1c65b4722da881fe"
[TSSC] manually specified ECID to use, parsed "1C48C81E22001E" to dec:7961323684102174 hex:1c48c81e22001e
[TSSC] manually specified apnonce to use, parsed "b0f3bab987cf096181fc2103182f271e91a7f9047386d02553ad9b48f96191b8" to hex:b0f3bab987cf096181fc2103182f271e91a7f9047386d02553ad9b48f96191b8
[TSSC] opening /private/var/folders/pz/s_t4pb8x3812k34c4q313spw0000gn/T/BuildManifest4816493452694535719.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

iOS 15.0 for device iPhone13,3 IS NOT being signed!
airsquared.blobsaver.app.TSS$TSSException: The iOS version is not being signed for device iPhone13,3
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.parseTSSLog(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)



```

**Comment by airsquared** [comment] 2021-09-21 04:44
Duplicate of #342 and fixed in v3.0.3.

**Closed by airsquared** 2021-09-21 04:44 UTC
Labels: duplicate
