### ISSUE TITLE
Unknown Error: JSON Issue?

### ISSUE THREAD

**Issue by anarchopossum** [airsquared/blobsaver#607] opened 2023-08-08 03:30 UTC
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
Ran the Program with the parameters listed below on image. I have tried with both devices listed on the right hand. Unknown Error was given.
**Screenshots**
![Screenshot 2023-08-07 at 8 23 54 PM](https://github.com/airsquared/blobsaver/assets/92814289/55a3f5c9-d0c8-4ced-a13b-b9f310141479)

**Desktop:**
 - OS Version: Mac OS 13.2.1
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked other open issues to see if my problem has already been reported
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.JsonParser.parseReader(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Network.makeJsonRequest(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getSignedBetas(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.syntaxError(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.checkLenient(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.doPeek(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.peek(Unknown Source)
	... 13 more

```

**Comment by rilodroid** [comment] 2023-08-08 22:11
Same here.

Blobsaver 3.5.1, macOS 13.2.1, IphoneX, 16.5.1, palera1n and iPhone7, 15.7, palera1n

**Comment by garyakimoto** [comment] 2023-08-10 02:23
same here, hope this bug will fixed

**Comment by airsquared** [comment] 2023-08-11 02:12
Thanks for the bug report; this is a duplicate of #603.

**Closed by airsquared** 2023-08-11 02:12 UTC
Labels: bug
