### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by AronL** [airsquared/blobsaver#343] opened 2021-09-20 20:55 UTC
In attempting to save the blobs for my iPhone 11 Pro on iOS 14.7RC, I am getting a strange error message that reads 'The iOS version is not being signed for device iPhone 12,3'

I was able to save blobs on blobsaver this morning.

In addition, I am still able to save blobs on shsh.host, although attempting to save iOS 15 blobs fails. (See second screenshot)

![2021-09-20](https://user-images.githubusercontent.com/21107428/134071284-c2201d81-3799-416d-b44a-617b3d17d43f.png)
![2021-09-20 (1)](https://user-images.githubusercontent.com/21107428/134073985-50adf22a-0fc9-4cc1-a318-c43a7c1313e6.png)

**Desktop:**
 - OS Version: Windows 10 Pro 21H1
 - iOS Device: 14.7RC

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by airsquared** [comment] 2021-09-21 04:44
Duplicate of #342 and fixed in v3.0.3.

**Closed by airsquared** 2021-09-21 04:44 UTC
Labels: duplicate
