### ISSUE TITLE
The iOS version is not being signed for device iPhone12,3

### ISSUE THREAD

**Issue by anafinotti** [airsquared/blobsaver#346] opened 2021-09-21 02:16 UTC
Describe the bug I cannot save blobs in my iPhone. I saved my device in blobsaver in August 27

Screenshots If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/5528817/134101704-b570f502-9343-4b8d-81c2-ed2a4e3f78c5.png)

Desktop:
* OS Version:macOS 11.6
* iOS Device: iPhone 11Pro 
* iOS Version: 13.3.1

Checklist (place an x between the brackets to mark as completed):
* [x ] I have made sure I am on the latest version of blobsaver
* [ x] I have checked the blobsaver wiki to see if there is already a solution to my problem
* [x ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

Log(s)
iosVersions = [IOSVersion[versionString=15.0, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-02879/CF24F586-A099-4E0C-A523-75ED6E459A7C/iPhone11,2,iPhone11,4,iPhone11,6,iPhone12,3,iPhone12,5_15.0_19A346_Restore.ipsw, signed=true], IOSVersion[versionString=14.8, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98087/C29E3FB8-8BDF-48F9-A794-C65E95629AF6/iPhone11,2,iPhone11,4,iPhone11,6,iPhone12,3,iPhone12,5_14.8_18H17_Restore.ipsw, signed=true], IOSVersion[versionString=14.7.1, ipswURL=https://updates.cdn-apple.com/2021SummerFCS/fullrestores/071-73966/B2F4517C-A57C-48D3-88B6-9A718A774EA6/iPhone11,2,iPhone11,4,iPhone11,6,iPhone12,3,iPhone12,5_14.7.1_18G82_Restore.ipsw, signed=true]]
Extracted to /var/folders/p6/lcyrngvd4zq2mt6f6_7311s00000gp/T/BuildManifest5427258889666506627.plist
Running: [/Applications/blobsaver.app/Contents/MacOS/tsschecker, --nocache, --save, --device, iPhone12,3, --ecid, 614E60AE1802E, --save-path, /Users/ana.finotti/Blobs, --boardconfig, d421ap, --apnonce, 5d367bcf42381fd368ef89ba33830c2b46c6554db17d4c266d602c89141a92af, --generator, 0x9fab1b7fb6c96b70, --build-manifest, /private/var/folders/p6/lcyrngvd4zq2mt6f6_7311s00000gp/T/BuildManifest5427258889666506627.plist]
tsschecker version: 1.0-4d5a39487d7f49c8cd23874c05c59dd38d010432
Libfragmentzip version: 7951fa1e40415a630cd2d4401b2ebb261b0a46a2 - 53
[TSSC] manually specified generator "0x9fab1b7fb6c96b70"
[TSSC] manually specified ECID to use, parsed "614E60AE1802E" to dec:1711828117848110 hex:614e60ae1802e
[TSSC] manually specified apnonce to use, parsed "5d367bcf42381fd368ef89ba33830c2b46c6554db17d4c266d602c89141a92af" to hex:5d367bcf42381fd368ef89ba33830c2b46c6554db17d4c266d602c89141a92af
[TSSC] opening /private/var/folders/p6/lcyrngvd4zq2mt6f6_7311s00000gp/T/BuildManifest5427258889666506627.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Checking BuildIdentity 2
[TSSR] Checking BuildIdentity 3
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

iOS 15.0 for device iPhone12,3 IS NOT being signed!
airsquared.blobsaver.app.TSS$TSSException: The iOS version is not being signed for device iPhone12,3
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.parseTSSLog(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by airsquared** [comment] 2021-09-21 04:46
Duplicate of #342 and fixed in v3.0.3.

**Closed by airsquared** 2021-09-21 04:46 UTC
Labels: duplicate
