### ISSUE TITLE
12.1.3 not found

### ISSUE THREAD

**Issue by spockers** [airsquared/blobsaver#36] opened 2019-01-23 01:24 UTC
iOS 12.1.3 dropped a few hours ago.

If I use "latest" option I get 12.1.2 blobs. If I manually specify 12.1.3, I get "could not find device on iOS 12.1.3."

Has Apple changed something recently?

Using v2.2.1 on Mojave.

**Comment by airsquared** [comment] 2019-01-23 03:30
Sometimes it takes a few hours to recognize a new version. Try again now, it should work.

**Comment by spockers** [comment] 2019-01-23 03:36
No dice. It's not an emergency, I'll check it again tomorrow. Thanks.

**Comment by airsquared** [comment] 2019-01-23 03:37
I'll close this, reopen it if the issue is still there.

**Closed by airsquared** 2019-01-23 03:37 UTC
Labels: bug

**Comment by SwiftWinds** [comment] 2019-01-23 07:03
Maybe elaborate on what device you're using? Maybe check the logs (Windows -> Open/Close Debug log)?

**Comment by spockers** [comment] 2019-01-23 12:14
6s and 2 5s's. Log window is empty. Maybe there's a cache somewhere I need to clear.

**Comment by SwiftWinds** [comment] 2019-01-25 15:13
Glad it could be resolved 👍
