### ISSUE TITLE
error

### ISSUE THREAD

**Issue by biertester** [airsquared/blobsaver#588] opened 2023-06-26 13:30 UTC
tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.1-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
[TSSC] manually specified generator "0x2624b02187c584e9"
[TSSC] manually specified ECID to use, parsed "115C4C0C20001E" to dec:4886556294774814 hex:115c4c0c20001e
[TSSC] manually specified apnonce to use, parsed "d60ba73bb462c0383af2a10b718495fabf202d7f103a5aef9fdc964413a8344f" to hex:d60ba73bb462c0383af2a10b718495fabf202d7f103a5aef9fdc964413a8344f
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!

**Comment by airsquared** [comment] 2023-06-26 23:24
Duplicate of #577.

**Closed by airsquared** 2023-06-26 23:24 UTC
Labels: duplicate
