### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iSmokeFlower** [airsquared/blobsaver#271] opened 2021-05-23 02:31 UTC
lockdownnd error: code=-23
![Desktop Screenshot 2021 05 22 - 21 30 18 55](https://user-images.githubusercontent.com/84650228/119246163-f6570380-bb44-11eb-97db-e6e309e478f8.png)

-------------------------------------------------------------

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [ ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment] 2021-05-23 02:33
This is a duplicate of #258. This issue should be solved in the v3.0 beta, if you are still having the issue please comment there.

**Closed by airsquared** 2021-05-23 02:33 UTC
Labels: bug
