### ISSUE TITLE
Blob saving does not work for Apple TV 4

### ISSUE THREAD

**Issue by ceedveed** [airsquared/blobsaver#162] opened 2020-05-23 16:20 UTC
Please remove the following line and the text above it before submitting this issue:

**Describe the bug**
Apple TV 4 results in "Saving blobs failed" message. No blobs saved when folder checked. There are no issues when using the TSS Saver website https://tsssaver.1conan.com/. Otherwise, Blobsaver works for my other idevices, iPhone X, iPad Pro 10.5, iPhone 7 Plus.

**Screenshots**
![image](https://user-images.githubusercontent.com/22138700/82735336-9423b280-9ce6-11ea-8bda-321d35b8e006.png)

**Desktop:**
 - OS Version: Windows 10 1909
 - iOS Device: (if applicable)
 - Java:
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
Version: 0ab4c4452a5a6a4f48ab7039560456051348b657 - 1
libfragmentzip version: 0.1-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "[redacted]" to dec:[redacted] hex:[redacted]
[TSSC] opening C:\Users\User\AppData\Local\Temp\BuildManifest183595788912959729.plist
[TSSR] LOG: device Appletv5,3 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] LOG: device Appletv5,3 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)

```

**Comment by airsquared** [comment] 2020-06-03 18:25
Closing as duplicate of #144. (please see that issue for updates)

**Closed by airsquared** 2020-06-03 18:25 UTC
Labels: duplicate
