### ISSUE TITLE
Create an option to facilitate remote saving at tsssaver.1conan.com

### ISSUE THREAD

**Issue by bs286692** [airsquared/blobsaver#224] opened 2020-12-28 03:14 UTC
**Describe the what you'd like**
Create an option to use appropriate APIs to facilitate remote saving at tsssaver.1conan.com.

Related to #206.

**Comment by nyuszika7h** [comment] 2021-03-31 12:51
This is pretty much a duplicate of #206.

**Comment by airsquared** [comment] 2021-05-20 01:05
Oh yeah it is a duplicate, seems I missed that. I'll edit this issue to make it just for tsssaver.1conan.com since the other one is for shsh.host.

**Comment by airsquared** [comment] 2022-04-03 19:17
Added in v3.1.0

**Closed by airsquared** 2022-04-03 19:17 UTC
Labels: enhancement, Pending Release
