### ISSUE TITLE
Unknown Error (MalformedJsonException) when saving beta blobs

### ISSUE THREAD

**Issue by plowsec** [airsquared/blobsaver#603] opened 2023-08-03 13:39 UTC
**Describe the bug**

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.JsonParser.parseReader(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Network.makeJsonRequest(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getSignedBetas(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.syntaxError(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.checkLenient(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.doPeek(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.peek(Unknown Source)
	... 13 more
```

**Screenshots**

<img width="360" alt="image" src="https://github.com/airsquared/blobsaver/assets/13260466/5823ec82-5c4e-4503-a024-516bfe3610d2">

**Desktop:**
 - OS Version: a development laptop with macOS 12.6.6
 - iOS Device: 15.6, iPhone X

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Comment by yodaluca23** [comment] 2023-08-06 03:34
This is happening to me too, XR 15.4

**Comment by LunarN0v4** [comment] 2023-08-06 12:16
Happening on Arch Linux with an iPhone 12 iOS 16.5.1

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.JsonParser.parseReader(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Network.makeJsonRequest(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getSignedBetas(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.syntaxError(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.checkLenient(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.doPeek(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.peek(Unknown Source)
	... 13 more

**Comment by airsquared** [comment] 2023-08-11 02:11
This is due to the beta API blobsaver is using no longer working. Looking for another solution, no ETA on a fix. In the meanwhile, you will have to disable including betas.

**Comment by garyakimoto** [comment] 2023-08-11 02:35
> 

So is that mean we can just uncheck save for beta option and get it work untill this problem was fix right? thanks

**Comment by airsquared** [comment] 2023-08-11 02:36
> So is that mean we can just uncheck save for beta option and get it work untill this problem was fix right? thanks

Yes

**Comment by Ruuka6009** [comment] 2023-08-18 23:59
happening to me too, sadly I am on 14 pro max using 17.0

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.JsonParser.parseReader(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Network.makeJsonRequest(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getSignedBetas(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.syntaxError(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.checkLenient(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.doPeek(Unknown Source)
	at com.google.gson@2.10.1/com.google.gson.stream.JsonReader.peek(Unknown Source)
	... 13 more

**Comment by airsquared** [comment] 2023-08-21 02:00
The error message is now clearer in v3.5.2 and I will be closing this in favor of #614, please follow the issue there.

**Closed by airsquared** 2023-08-21 02:00 UTC
Labels: bug
