### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Toantd00** [airsquared/blobsaver#535] opened 2023-01-04 17:14 UTC
Iphone 11 
Ios 15.6.1
![image](https://user-images.githubusercontent.com/92044099/210611803-30689152-d741-4109-9047-592fd227af71.jpeg)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
 at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
 at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
 at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
 at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
 at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.saveBlobsSHSHHost(Unknown Source)
 at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
 at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
 at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
 at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
 at com.google.gson@2.10/com.google.gson.stream.JsonReader.beginObject(Unknown Source)
 at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
 at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
 ... 12 more

**Comment by airsquared** [comment] 2023-01-07 10:55
Duplicate of https://github.com/airsquared/blobsaver/issues/530. Please check there for more information.

**Closed by airsquared** 2023-01-07 10:55 UTC
Labels: duplicate
