### ISSUE TITLE
An unknown error has occured.

### ISSUE THREAD

**Issue by supersun171** [airsquared/blobsaver#601] opened 2023-07-29 16:11 UTC
blobsaver just says "An unknown error has occured."

![image](https://github.com/airsquared/blobsaver/assets/140907752/6c410582-9845-485e-ae6e-e5f3fe660d18)

 - OS Version: Windows 10
 - iOS Device: iPhone 5

Here's the log:

java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonArray.spliterator()" because "<local3>" is null
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getSignedBetas(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by airsquared** [comment] 2023-08-11 02:42
Even though this is not an exact duplicate; the fix will be the same so I will close this as a duplicate of #603.

**Closed by airsquared** 2023-08-11 02:42 UTC
Labels: bug, duplicate
