### ISSUE TITLE
Error Saving Blobs

### ISSUE THREAD

**Issue by vilzio** [airsquared/blobsaver#536] opened 2023-01-04 20:39 UTC
**Describe the bug**
When I try to save blobs, it just gives me an error and won't save it.

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/93621816/210644821-b8e03c69-6060-4302-8f9d-64895a35d27c.png)

**Desktop:**
 - OS Version: 15.5 (19F5070b)
 - iOS Device: iPad (8th generation)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of Blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [ ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling Blobsaver

**Log(s)**
```
It said, "The log has been copied to your clipboard," but I don't have them copied. If there's a file of the logs, I'll send that. 
```

**Comment by vilzio** [comment] 2023-01-04 20:42
this seems to big a big issue because i checked and alot of people have the same issue

**Comment by airsquared** [comment] 2023-01-07 10:54
Duplicate of #530. Please check there for more information.

**Closed by airsquared** 2023-01-07 10:54 UTC
Labels: duplicate
