### ISSUE TITLE
Failed to load manifest

### ISSUE THREAD

**Issue by tgod34748** [airsquared/blobsaver#585] opened 2023-06-20 19:00 UTC
**Describe the bug**
When I try to save blobs for my iPhone SE 3, using the newest release of blobsaver, it fails and says "Failed to load manifest". 

**Screenshots**
<img width="472" alt="Screenshot 2023-06-20 at 1 50 13 PM" src="https://github.com/airsquared/blobsaver/assets/129342366/bd52e18e-9759-4201-b9fe-607e5d56fedb">

**Desktop:**
 - OS Version: macOS 13.4 - MacBook Air (M1, 2020)
 - iOS Device: iPhone SE (3rd generation) - iOS 16.5

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.1-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
[TSSC] manually specified generator "0x0865cf99824f7242"
[TSSC] manually specified ECID to use, parsed "215E91E44401E" to dec:587040932773918 hex:215e91e44401e
[TSSC] manually specified apnonce to use, parsed "8005374ad9c31cfbc139bcffb70cd1abc372a6bceaf58127661759ff5f521f88" to hex:8005374ad9c31cfbc139bcffb70cd1abc372a6bceaf58127661759ff5f521f88
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!

**Comment by chrisharper22** [comment] 2023-06-20 21:31
Having this issue with an iPad Air (5th generation) on 16.2:

```tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.1-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
[TSSC] manually specified generator "0xa59415b11afd81de"
[TSSC] manually specified ECID to use, parsed "D49A60C20801E" to dec:3740152214093854 hex:d49a60c20801e
[TSSC] manually specified apnonce to use, parsed "a2ddd828e8ce38feb73846cf8d078e5d9713708553de848523b7a694bbfd5f64" to hex:a2ddd828e8ce38feb73846cf8d078e5d9713708553de848523b7a694bbfd5f64
[Error] [TSSC] failed to load manifest

[Error] [TSSC] checking tss status failed!
```

**Comment by anarchopossum** [comment] 2023-06-23 01:55
I have also been having this issue with a similar log.
This issue is with an iphone 13 Mini 16.3.1

**Comment by airsquared** [comment] 2023-06-26 23:23
Duplicate of #577.

**Closed by airsquared** 2023-06-26 23:23 UTC
Labels: duplicate
